spring:
  profiles:
    active:
      - development
  application:
    name: "Spring Boot 3 Todo List"
  datasource:
    url: jdbc:postgresql://<DB_URL>:5432/postgres?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: postgres
    password: <your_password>
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: <REDIS URL>
      port: <PORT>
      timeout: 10000ms
      username: <USERNAME>
      password: <PASSWORD>
  jpa:
    hibernate:
        ddl-auto: update
  graphql:
    path: /api/v1/graphql
    graphiql:
      enabled: true
      path: /graphiql
springdoc:
  api-docs:
    path: /api-docs
    version: openapi_3_0
  swagger-ui:
    operations-sorter: method
    path: /swagger-ui.html
    version: 3.0.0